--1
CREATE TABLE PERSON
(
DRIVER_ID VARCHAR2(10),
NAME VARCHAR2(20),
ADDRESS VARCHAR2(15),
PRIMARY KEY(DRIVER_ID)
);

CREATE TABLE CAR
(
REGNO VARCHAR2(10),
MODEL VARCHAR2(10),
YEAR NUMBER(4),
PRIMARY KEY(REGNO)
);

CREATE TABLE ACCIDENT
(
REPORT_NO NUMBER(5);
ADATE DATE,
LOCATION VARCHAR2(15),
PRIMARY KEY(REPORT_NO)
);

CREATE TABLE OWNS
(
DRIVER_ID VARCHAR2(10),

REGNO VARCHAR2(10),
PRIMARY KEY(DRIVER_ID,REGNO),
FOREIGN KEY(DRIVER_ID) REFERENCES PERSON(DRIVER_ID),
FOREIGN KEY(REGNO) REFERENCES CAR(REGNO)
);

CREATE TABLE PARTICIPATED
(
DRIVER_ID VARCHAR2(10),
REGNO VARCHAR2(10),
REPORT_NO NUMBER(5),
DAMAGE_AMT NUMBER(7,2),
PRIMARY KEY(DRIVER_ID,REGNO,REPORT_NO),
FOREIGN KEY(DRIVER_ID,REGNO) REFERENCES OWNS(DRIVER_ID,REGNO) ON DELETE CASCADE,
FOREIGN KEY(REPORT_NO) REFERENCES ACCIDENT(REPORT_NO) ON
DELETE CASCADE
);

--2
INSERT INTO PERSON VALUES
(&#39;&amp;DRIVER_ID&#39;,&#39;&amp;NAME&#39;,&#39;&amp;ADDRESS&#39;);
SELECT * FROM PERSON

INSERT INTO CAR VALUES
(&#39;&amp;REGNO&#39;,&#39;&amp;MODEL&#39;,&amp;YEAR);
SELECT * FROM CAR

INSERT INTO ACCIDENT VALUES
(&amp;REPORT_NO,&#39;&amp;ADATE&#39;,&#39;&amp;LOCATION&#39;);
SELECT * FROM ACCIDENT

INSERT INTO OWNS VALUES
(&#39;&amp;DRIVER_ID&#39;,&#39;&amp;REGNO&#39;);
SELECT * FROM OWNS

DELETE FROM OWNS WHERE DRIVER_ID = &#39;3433&#39;;

INSERT INTO PARTICIPATED VALUES
(&#39;&amp;DRIVER_ID&#39;,&#39;&amp;REGNO&#39;,&#39;&amp;REPORT_NO&#39;,&amp;DAMAGE_AMT);
SELECT * FROM PARTICIPATED

--3 VIEWING

SELECT * FROM PERSON

SELECT * FROM CAR

SELECT * FROM ACCIDENT

SELECT * FROM OWNS

SELECT * FROM PARTICIPATED

--4
UPDATE PARTICIPATED
SET DAMAGE_AMT=25000
WHERE REPORT_NO =12 AND REGNO=&#39;KA 22 1032&#39;;
SELECT * FROM PARTICIPATED

--5
SELECT COUNT(*) FROM ACCIDENT
WHERE ADATE LIKE &#39;20-02-19&#39;;

--6
SELECT COUNT(A.REPORT_NO)
FROM ACCIDENT A, PARTICIPATED P, CAR C
WHERE A.REPORT_NO=P.REPORT_NO
AND
P.REGNO=C.REGNO
AND
C.MODEL=&#39;PORCHE&#39;;