CREATE TABLE CUSTOMERS(CUST_NO NUMBER(3),CNAME VARCHAR(10),CITY
VARCHAR2(20),PRIMARY KEY(CUST_NO));

CREATE TABLE ORDERS(ORDER_NO NUMBER(3),O_DATE DATE,CUST_NO NUMBER(3),ORD_AMT
REAL,PRIMARY KEY(ORDER_NO),FOREIGN KEY(CUST_NO) REFERENCES CUSTOMERS);

CREATE TABLE ITEM(ITEM_NO NUMBER(3),UNIT_PRICE REAL,PRIMARY KEY(ITEM_NO));

CREATE TABLE ORDER_ITEM(ORDER_NO NUMBER(3),ITEM_NO NUMBER(3),QTY
NUMBER(3),PRIMARY KEY(ORDER_NO,ITEM_NO),FOREIGN KEY(ORDER_NO) REFERENCES
ORDERS,FOREIGN KEY(ITEM_NO) REFERENCES ITEM);

CREATE TABLE WAREHOUSE(WAREHOUSE_NO NUMBER(3), CITY VARCHAR2(20),PRIMARY
KEY(WAREHOUSE_NO));

CREATE TABLE SHIPMENT(ORDER_NO NUMBER(3),WAREHOUSE_NO NUMBER(3),SHIP_DATE
DATE,FOREIGN KEY(ORDER_NO) REFERENCES ORDERS,FOREIGN KEY(WAREHOUSE_NO) REFERENCES
WAREHOUSE);

INSERT INTO CUSTOMERS VALUES(&amp;CUST_NO,&#39;&amp;CNAME&#39;,&#39;&amp;CITY&#39;);

SELECT * FROM CUSTOMERS;

INSERT INTO ORDERS VALUES(&amp;ORDER_NO,&#39;&amp;O_DATE&#39;,&amp;CUST_NO,&amp;ORD_AMT);

SELECT * FROM ORDERS;

INSERT INTO ITEM VALUES(&amp;ITEM_NO,&amp;UNIT_PRICE);

SELECT * FROM ITEM;

INSERT INTO ORDER_ITEM VALUES(&amp;OREDR_NO,&amp;ITEM_NO,&amp;QTY);

SELECT * FROM ORDER_ITEM;

INSERT INTO WAREHOUSE VALUES(&amp;WAREHOUSE_NO,&#39;&amp;CITY&#39;);

SELECT * FROM WAREHOUSE;

INSERT INTO SHIPMENT VALUES(&amp;ORDER_NO,&amp;WAREHOUSE_NO,&#39;&amp;SHIP_DATE&#39;);

SELECT * FROM SHIPMENT;